// This file is auto-generated by emdash. Do not edit manually.
// Run `pnpm dev` to regenerate.

import type { PortableTextBlock } from "emdash";

interface Page {
  id: string;
  slug: string;
  status: string;
  title: string;
  content: PortableTextBlock[];
  createdAt: string;
  updatedAt: string;
  publishedAt: string | null;
}

interface Post {
  id: string;
  slug: string;
  status: string;
  title: string;
  content: PortableTextBlock[];
  excerpt: string | null;
  featured_image: {
    id: string;
    src: string;
    alt: string;
    width: number;
    height: number;
  } | null;
  createdAt: string;
  updatedAt: string;
  publishedAt: string | null;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    posts: Post;
  }
}
